### Without Gateway

http://localhost:9002/value

### With Gateway

http://localhost:9000/aggregator/value

### With Token & Gateway

http://localhost:9000/aggregator/value
Authorization: top-secret



###

POST http://localhost:64657/api/payments
Content-Type: application/json

{
  "type": "payment",
  "id": 2,
  "senderId": 1,
  "amount": 100,
  "comment": "xyz"
}

###

POST http://localhost:9000/producer/api/payments
Content-Type: application/json

{
  "type": "payment",
  "id": -55,
  "senderId": -51,
  "amount": -100,
  "comment": "OKA5555555333333333333333333333335AY"
}

###

GET http://localhost:9000/aggregator/api/payments


###
