### Without Gateway

http://localhost:9002/value

### With Gateway

http://localhost:9000/aggregator/value

### With Token & Gateway

http://localhost:9000/aggregator/value
Authorization: top-secret



###

POST http://localhost:64657/api/payments
Content-Type: application/json

{
  "type": "payment",
  "id": 2,
  "senderId": 1,
  "amount": 100,
  "comment": "xyz"
}

###

POST http://localhost:9000/producer/api/payments
Content-Type: application/json

{
  "type": "payment",
  "id": 1,
  "senderId": 6666555555555555,
  "amount": 1000,
  "comment": "FOR TEA2"
}

###

GET http://localhost:9000/aggregator/api/payments


###
